version: '3.9'
name: "pwa_app"
services:
  postgres:
    container_name: postgres
    image: postgres:13-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - '6500:5432'
    env_file:
      - ./app.env
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - pwa_app

  server:
    build: Backend
    container_name: server-api
    ports:
      - '8000:8000'
    volumes:
      - ./Backend:/app/
    depends_on:
      - postgres
    env_file:
      - ./app.env
    networks:
      - pwa_app
    command:
      - /bin/sh
      - -c
      - |
        go run main.go
        tail -f /dev/null


  web:
    build: Frontend
    container_name: web
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - ./Frontend/:/app/
      - ignore:/app/node_modules
    env_file:
      - ./app.env
    command:
      - /bin/bash
      - -c
      - |
        npm run start
        tail -f /dev/null

volumes:
  postgres_data:
  ignore:
networks:
  pwa_app:
    driver: bridge
