version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '6500:5432'
    volumes:
      - progresDB:/var/lib/postgresql/data
    env_file:
      - app.env
    networks:
      - pwa_app

  server:
    image: golang-api:latest
    container_name: server-api
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    networks:
      - pwa_app
volumes:
  progresDB:
networks:
  pwa_app:
    driver: bridge
